// Mocks generated by Mockito 5.4.6 from annotations
// in domain/test/usecases/use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:domain/src/entities/course.dart' as _i4;
import 'package:domain/src/entities/reminder.dart' as _i8;
import 'package:domain/src/entities/task.dart' as _i6;
import 'package:domain/src/repositories/course_repository.dart' as _i2;
import 'package:domain/src/repositories/reminder_repository.dart' as _i7;
import 'package:domain/src/repositories/task_repository.dart' as _i5;
import 'package:domain/src/services/notification_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i2.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Course>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.Course>>.empty(),
          )
          as _i3.Stream<List<_i4.Course>>);

  @override
  _i3.Future<_i4.Course?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<_i4.Course?>.value(),
          )
          as _i3.Future<_i4.Course?>);

  @override
  _i3.Future<void> save(_i4.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#save, [course]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i5.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.Task>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i6.Task>>.empty(),
          )
          as _i3.Stream<List<_i6.Task>>);

  @override
  _i3.Stream<List<_i6.Task>> watchByDueDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#watchByDueDate, [date]),
            returnValue: _i3.Stream<List<_i6.Task>>.empty(),
          )
          as _i3.Stream<List<_i6.Task>>);

  @override
  _i3.Future<_i6.Task?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<_i6.Task?>.value(),
          )
          as _i3.Future<_i6.Task?>);

  @override
  _i3.Future<void> save(_i6.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#save, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markDone(String? id, {required bool? done}) =>
      (super.noSuchMethod(
            Invocation.method(#markDone, [id], {#done: done}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ReminderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderRepository extends _i1.Mock
    implements _i7.ReminderRepository {
  MockReminderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i8.Reminder>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i8.Reminder>>.empty(),
          )
          as _i3.Stream<List<_i8.Reminder>>);

  @override
  _i3.Future<_i8.Reminder?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<_i8.Reminder?>.value(),
          )
          as _i3.Future<_i8.Reminder?>);

  @override
  _i3.Future<void> save(_i8.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#save, [reminder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setActive(String? id, {required bool? active}) =>
      (super.noSuchMethod(
            Invocation.method(#setActive, [id], {#active: active}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> schedule(_i8.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#schedule, [reminder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancel(String? reminderId) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [reminderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
